export const CONTROL_CONFIG = {
  apiBaseUrl: '',
  customApiName: 'voa_GetAllSalesRecord',
  customApiType: 'function',
  metadataApiName: 'voa_SvtGetSalesMetadata',
  metadataApiType: 'function',
  viewSaleRecordApiName: 'voa_GetViewSaleRecordById',
  tableKey: 'sales',
  serverDrivenThreshold: 2000,
  taskAssignmentApiName: 'voa_SvtTaskAssignment',
  assignableUsersApiName: 'voa_SvtGetAssignableUsers',
  assignableUsersApiType: 'function',
  emptyStateTitle: "We didn't find anything to show here",
  emptyStateMessage: 'Try adjusting your filters or search.',
  selectionControls: {
    toolbarAriaLabel: 'Table actions',
    groupAriaLabel: 'Page selection',
    selectAllText: 'Select all on this page',
    clearText: 'Clear selection',
    selectFirstLabel: 'Select first',
    selectFirstPlaceholder: 'Number',
    selectFirstSuffix: 'on this page',
    selectFirstButtonText: 'Apply',
    selectFirstHelperText: 'Uses the current page order.',
    selectFirstErrorText: 'Enter a number between 1 and {max}.',
    selectionSummaryText: 'Selected: {selected} of {pageTotal} on this page',
  },
  taskAssignment: {
    maxBatchSize: 500,
    allowedStatuses: ['New', 'Assigned', 'Assigned QC failed', 'QC requested'],
    loadingText: 'Please wait...',
    tooManyTasksMessage: 'Please select {max} tasks or fewer for batch assignment.',
    invalidStatusMessage: 'One or more selected tasks cannot be assigned based on status.',
  },
};
