export const CONTROL_CONFIG = {
  apiBaseUrl: '',
  customApiName: 'voa_GetAllSalesRecord',
  customApiType: 'function',
  metadataApiName: 'voa_SvtGetSalesMetadata',
  metadataApiType: 'function',
  userContextApiName: 'voa_SvtGetUserContext',
  userContextApiType: 'function',
  viewSaleRecordApiName: 'voa_GetViewSaleRecordById',
  viewSaleRecordApiType: 'function',
  auditLogsApiName: 'voa_SvtGetAuditLogs',
  auditLogsApiType: 'function',
  manualTaskCreationApiName: 'voa_SvtManualTaskCreation',
  manualTaskCreationApiType: 'action',
  modifyTaskApiName: 'voa_SvtModifyTask',
  modifyTaskApiType: 'action',
  submitSalesVerificationApiName: 'voa_SvtSubmitSalesVerification',
  submitSalesVerificationApiType: 'action',
  enableCountryListYearApiParams: false,
  enablePcfViewSalesDetails: false,
  tableKey: 'sales',
  serverDrivenThreshold: 2000,
  taskAssignmentApiName: 'voa_SvtTaskAssignment',
  taskAssignmentApiType: 'action',
  submitQcRemarksApiName: 'voa_SvtSubmitQcRemarks',
  submitQcRemarksApiType: 'action',
  assignableUsersApiName: 'voa_SvtGetAssignableUsers',
  assignableUsersApiType: 'function',
  taskAssignment: {
    maxBatchSize: 500,
    allowedStatusesManager: [
      'New',
      'Assigned',
      'Assigned QC failed',
      'QC requested',
    ],
    allowedStatusesQc: [
      'QC requested',
      'Complete',
      'Assigned QC failed',
      'Assigned To QC',
      'Reassigned To QC',
    ],
    // Fallback for non-assignment screens if needed.
    allowedStatuses: [],
  },
};

