import { SaleDetailsRecord } from './types';

export const SAMPLE_SALE_DETAILS: SaleDetailsRecord = {
  salesVerificationTaskDetails: {
    saleId: 'S-1000220',
    taskId: 'A-1000032',
    taskStatus: 'Assigned QC Failed',
    assignedTo: 'Avinaba Hazra',
    qcAssignedTo: 'Maria Augustine',
  },
  links: {
    vms: '',
    vmsX: '242742.0',
    vmsY: '221368.0',
    zoopla: 'sa31-2ae',
    rightMove: 'sa31-2ae',
    epc: 'SA31 2AE',
  },
  propertyAndBandingDetails: {
    address: '6 DOLGWILI ROAD, CARMARTHEN, SA31 2AE',
    suId: '5e6cc9c5-9ffe-8e43-b18e-29eb0ce3cba7',
    band: 'E',
    bandingEffectiveDate: '2005-04-01T00:00:00',
    billingAuthorityName: 'Carmarthenshire (1)',
    composite: false,
    padStatus: 'Committed',
    effectiveDate: '2025-03-18T00:00:00',
    effectiveTo: null,
    dwellingGroup: '32',
    dwellingType: 'HD',
    ageCode: '2025',
    dwellingArea: '152',
    heating: 'Yes',
    mainroomCount: 5,
    bedroomCount: 4,
    bathroomCount: 2,
    floorCount: 2,
    floorLevel: 'G1',
    parkingCode: 'V',
    reasonCode: 'N',
    conservatoryType: null,
    conservatoryArea: null,
    valueSignificantCodes: '0',
    sourceCodes: 'D2',
    plotSize: '235230',
    activeRequestInVos: true,
    padConfirmation: null,
    attributeTooltips: {
      dwellingGroup: 'Dwelling Group',
      dwellingType: 'Dwelling Type',
      ageCode: 'Age Code',
      dwellingArea: 'Area of Dwelling',
      mainroomCount: 'Rooms',
      bedroomCount: 'Bedrooms',
      bathroomCount: 'Bathrooms',
      floorCount: 'Floors',
      floorLevel: 'Level',
      parkingCode: 'Parking',
      reasonCode: 'Reason Code',
    },
  },
  masterSale: {
    salePrice: 200000,
    transactionDate: '2022-04-13T00:00:00',
    ratio: null,
    saleSource: 'LRPPD',
    hpiAdjustedPrice: 207012,
    reviewFlags: null,
    overallFlag: 'Investigate can use',
    summaryFlags: 'same solicitor',
    modelValue: 272973,
  },
  repeatsSaleInfo: {
    previousRatioRange: null,
    laterRatioRange: null,
  },
  welshLandTax: [
    {
      wlttId: '21751E75-F332-3A2C-2CED-D1CB79398385',
      transactionPrice: 200000,
      transactionPremium: null,
      transactionDate: '2022-04-13T00:00:00',
      groundRent: null,
      vendors: 'GALE WILLIAM',
      vendees: 'JENKINS HELEN, JONES DAVID',
      vendorAgents: 'JENNIFER MELLY LAW LTD',
      vendeeAgents: 'MORGAN ELIS LIMITED',
      typeOfProperty: 'L',
      tenureType: 'FP',
      leaseFrom: null,
      leaseTerm: null,
      hpiAdjustedPrice: 207012,
      ratio: null,
    },
    {
      wlttId: 'A1751E75-F332-3A2C-2CED-D1CB79398386',
      transactionPrice: 198500,
      transactionPremium: 0,
      transactionDate: '2022-03-18T00:00:00',
      groundRent: 0,
      vendors: 'SAMPLE VENDOR',
      vendees: 'SAMPLE VENDEE',
      vendorAgents: 'EXAMPLE LAW LLP',
      vendeeAgents: 'EXAMPLE CONVEYANCING',
      typeOfProperty: 'L',
      tenureType: 'FP',
      leaseFrom: null,
      leaseTerm: null,
      hpiAdjustedPrice: 205106,
      ratio: null,
    },
  ],
  landRegistryData: [
    {
      lrppdId: '045A1898-6F5E-9A24-E063-4804A8C048EA',
      address: '6 DOLGWILI ROAD',
      transactionPrice: 200000,
      typeOfProperty: 'S',
      tenureType: 'F',
      oldNew: 'N',
      transactionDate: '2022-04-13T00:00:00',
      pricePaidCategory: 'A',
      hpiAdjustedPrice: 207012,
      ratio: null,
    },
    {
      lrppdId: '145A1898-6F5E-9A24-E063-4804A8C048FA',
      address: '6 DOLGWILI ROAD',
      transactionPrice: 198500,
      typeOfProperty: 'S',
      tenureType: 'F',
      oldNew: 'N',
      transactionDate: '2022-03-18T00:00:00',
      pricePaidCategory: 'A',
      hpiAdjustedPrice: 205106,
      ratio: null,
    },
  ],
  salesParticularDetails: {
    salesParticular: 'Not reviewed',
    linkParticulars: null,
    kitchenAge: null,
    kitchenSpecification: null,
    bathroomAge: null,
    bathroomSpecification: null,
    glazing: null,
    heating: null,
    decorativeFinishes: null,
    conditionScore: null,
    conditionCategory: null,
    particularNotes: null,
    attributeTooltips: {
      kitchenAge: 'Compare kitchen age image references from SharePoint',
      kitchenSpecification: 'Compare kitchen specification image references from SharePoint',
      bathroomAge: 'Compare bathroom age image references from SharePoint',
      bathroomSpecification: 'Compare bathroom specification image references from SharePoint',
      decorativeFinishes: 'Compare decorative finishes image references from SharePoint',
    },
    referenceImages: [
      {
        id: 'ref-k-age-1',
        attributeKey: 'kitchenAge',
        category: 'Dated',
        title: 'Kitchen Example A',
        imageUrl: 'https://picsum.photos/seed/svt-kitchen-aged-1/420/280',
        sourceUrl: 'https://contoso.sharepoint.com/sites/svt/Shared%20Documents/kitchen-aged-1.jpg',
      },
      {
        id: 'ref-k-age-2',
        attributeKey: 'kitchenAge',
        category: 'Modern',
        title: 'Kitchen Example B',
        imageUrl: 'https://picsum.photos/seed/svt-kitchen-modern-1/420/280',
        sourceUrl: 'https://contoso.sharepoint.com/sites/svt/Shared%20Documents/kitchen-modern-1.jpg',
      },
      {
        id: 'ref-k-spec-1',
        attributeKey: 'kitchenSpecification',
        category: 'High',
        title: 'Kitchen Spec High',
        imageUrl: 'https://picsum.photos/seed/svt-kitchen-spec-high/420/280',
        sourceUrl: 'https://contoso.sharepoint.com/sites/svt/Shared%20Documents/kitchen-spec-high.jpg',
      },
      {
        id: 'ref-b-age-1',
        attributeKey: 'bathroomAge',
        category: 'Dated',
        title: 'Bathroom Example A',
        imageUrl: 'https://picsum.photos/seed/svt-bath-aged-1/420/280',
        sourceUrl: 'https://contoso.sharepoint.com/sites/svt/Shared%20Documents/bath-aged-1.jpg',
      },
      {
        id: 'ref-b-spec-1',
        attributeKey: 'bathroomSpecification',
        category: 'Standard',
        title: 'Bathroom Spec Standard',
        imageUrl: 'https://picsum.photos/seed/svt-bath-spec-standard/420/280',
        sourceUrl: 'https://contoso.sharepoint.com/sites/svt/Shared%20Documents/bath-spec-standard.jpg',
      },
      {
        id: 'ref-fin-1',
        attributeKey: 'decorativeFinishes',
        category: 'Average',
        title: 'Decorative Finishes Example',
        imageUrl: 'https://picsum.photos/seed/svt-finish-average/420/280',
        sourceUrl: 'https://contoso.sharepoint.com/sites/svt/Shared%20Documents/decorative-finish-1.jpg',
      },
    ],
  },
  auditHistory: {
    taskId: 'A-1000032',
    auditHistory: [
      {
        changeID: 1,
        changedBy: 'Maria Augustine',
        changedOn: '2026-03-11T15:22:49Z',
        eventType: 'Update',
        changes: [
          { fieldName: 'TaskStatus', oldValue: 'Assigned To QC', newValue: 'Assigned QC Failed' },
        ],
      },
      {
        changeID: 2,
        changedBy: 'Maria Augustine',
        changedOn: '2026-03-11T14:34:01Z',
        eventType: 'Update',
        changes: [
          { fieldName: 'TaskStatus', oldValue: 'QC Requested', newValue: 'Assigned To QC' },
          { fieldName: 'QCAssignedTo', oldValue: '-', newValue: 'Maria Augustine' },
        ],
      },
      {
        changeID: 3,
        changedBy: 'Avinaba Hazra',
        changedOn: '2026-03-11T00:03:50Z',
        eventType: 'Update',
        changes: [
          { fieldName: 'TaskStatus', oldValue: 'Assigned', newValue: 'QC Requested' },
        ],
      },
    ],
  },
  qcAuditHistory: {
    taskId: 'A-1000032',
    auditHistory: [
      {
        changeID: 7,
        changedBy: 'Maria Augustine',
        changedOn: '2026-03-11T15:22:49Z',
        eventType: 'QC',
        changes: [
          { fieldName: 'Outcome', oldValue: '-', newValue: 'Fail' },
          { fieldName: 'QCRemarks', oldValue: '-', newValue: 'Insufficient comparable evidence' },
        ],
      },
    ],
  },
  salesVerificationDetails: {
    isSaleUseful: null,
    whyNotUseful: null,
    additionalNotes: null,
    remarks: null,
  },
  qualityControlOutcome: {
    qcOutcome: 'Fail',
    qcRemark: 'qc failed',
    qcReviewedBy: 'Maria Augustine',
  },
};

export const SAMPLE_USER_LOOKUP: Record<string, string> = {
  'c093b3e8-1641-f011-877a-002248c68e0b': 'Avinaba Hazra',
  '56ec660c-c908-f011-bae3-6045bd0e1fbf': 'Maria Augustine',
};



